Repository ynput/ayon-python-api, pull requests merged in 2024-11, with the labels that each got.

#207 Chore: Implement delete event method
  ayon_api/__init__.py
  ayon_api/_api.py
  ayon_api/server_api.py
Labels: type: enhancement

#210 Delete addon endpoints
  ayon_api/__init__.py
  ayon_api/_api.py
  ayon_api/server_api.py
Labels: type: enhancement

#202 Chore: Implement sender type support
  ayon_api/__init__.py
  ayon_api/_api.py
  ayon_api/server_api.py
Labels: type: enhancement

#197 Entity hub: Small refactor and add product & version
  ayon_api/constants.py
  ayon_api/entity_hub.py
Labels: type: enhancement

#204 Fix thumbnail mime type calculation
  ayon_api/server_api.py
  ayon_api/utils.py
Labels: type: bug

#211 Chore: Public api does automatically fill in all arguments with typehints
  automated_api.py
  ayon_api/_api.py
Labels: type: enhancement

#213 Representations hierarchy: Handle fields same way as in other functions
  ayon_api/server_api.py
Labels: type: bug

#215 Chore: As username stack works
  ayon_api/server_api.py
Labels: type: bug

#209 Activities endpoints
  automated_api.py
  ayon_api/__init__.py
  ayon_api/_api.py
  ayon_api/_typing.py
  ayon_api/constants.py
  ayon_api/graphql_queries.py
  ayon_api/server_api.py
Labels: type: enhancement

#217 Tests: EntityHub updates
  ayon_api/entity_hub.py
  tests/conftest.py
  tests/test_entity_hub.py
  tests/test_get_events.py
  tests/test_server.py
Labels: type: enhancement

#219 As username functionality can ignore service user error
  ayon_api/server_api.py
Labels: type: enhancement

#221 Return task id when creating a task using the create task function
  ayon_api/server_api.py
Labels: type: bug, community

#220 Events: Use statuses for events filtering
  ayon_api/_api.py
  ayon_api/graphql_queries.py
  ayon_api/server_api.py
Labels: type: enhancement
